### ISSUE TITLE
Scribble App

### ISSUE THREAD

**Issue by M00staff** [ga-dc/scribble#26]
comfort 3
completeness 3

Live link: http://mooses-excuses.herokuapp.com/ 
Repo: https://github.com/M00staff/scribble

i just noticed (literally like 2 mins ago) that the sign in/up/out isn't working on the live link but works fine when i run rails s locally... Any idea why?

**Comment by andrewsunglaekim** [comment]
Could be alot of different reasons. Try running 

```
heroku config:set RAILS_ENV=development
```

in the terminal where your application lives(the one that you deployed to heroku)

this will turn your heroku rails environment to development where you can see more errors. I think i see a `sign_up` action as well as a `signup!` action, that may have something to do with it as well. 

I can also see that in one of your views you nested a `<ul>` inside of an each loop instead of an `<li>`. You should try to keep the list elements outside of your each loop, and the `<li>`'s inside.

Good job on this hw though :+1:
