### ISSUE TITLE
scribble on heroku hw

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/scribble#31]
https://adrians-scribble.herokuapp.com

comfort level = 3
completeness = 3

Did my best - a whole day's worth, it seemed - to get user and authentication going, but no joy. Only got as far as seeing the sign-in page and fields. Otherwise, had problem and never figured out a few broken routes around comments edits. Left styling until last hour or so; I will really need to find time somewhere, somehow to get a basic functional command of it. Really grinding metal on metal at this point; feel like I explored every outer limit of my knowledge and ability. Still a lot of work and practice to do.

**Comment by RobertAKARobin** [comment]
Judging by your Chill Out you really did take time to yourself this weekend, which I think is a very good thing. When you start your project, I anticipate you being excited to have a clean slate and surprised at how well you remember how some things should fit together.

I also anticipate you feeling really frustrated that there's something you _know_ you've done before, but now you don't remember how the stupid thing is supposed to work. Watch it for that: notice when it's happening, put a label on it, and think objectively about what the best use of your time is. If you can develop the skill of being able to do something else and come back to a problem later, you'll have developed something very valuable.

(And no CSS is better than bad CSS any day. See http://www.motherfuckingwebsite.com and http://www.bettermotherfuckingwebsite.com)

I like your "no comments" message. :)

I like your `seeds.rb`!

I appreciate that instead of leaving non-functioning authentication in your app, you took it out altogether. Drives me CRAZY when people do the opposite.

Might want to go a little easy on commenting out code. Several of your controllers have their code pretty much duplicated as comments.

Nicely done!
