### ISSUE TITLE
scribble HW

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-dc/scribble#38]
Understanding material: 4 (getting concepts)
Comfort: 3.5 (actually making the stuff)
Completeness: 5

github: https://github.com/omarimayerswalker/scribble_final
heroku: https://omari-scribble-final.herokuapp.com/

I got it done but I still don't feel comfortable with troubleshooting bugs. Some how I didn't create my db with postgresql, so I had problems deploying. I'm not comfortable with how much copy and pasting I did to complete this, but I am getting more comfortable with the overall process.

**Comment by RobertAKARobin** [comment]
Instead of having a `scribble_final` repo, just create a `final` branch in your regular `scribble` repo!

Hmm. I'm unable to actually create a post — I get a "The change you wanted was rejected." error. But I seem to have successfully created a user!

Why didn't you just `rails new` again and copy your files over to solve the database problem? I remember recommending this.

Nice CSS!

There's nothing wrong with copying and pasting, as long as you give credit where it's due. Relevant image: https://pbs.twimg.com/media/BCh-v51CAAA9HuT.jpg

**Comment by omarimayerswalker** [comment]
Hi Robin, I was able to sign up and sign in right now. You might need to sign in after signing up... I didn't fix that before deploying.

I did do a `rails new` and copied my files over like you recommended. I wanted to change the name of the directory so I wouldn't get the two mixed up.
