### ISSUE TITLE
Scribble App HW

### ISSUE THREAD

**Issue by skey08** [ga-dc/scribble#41]
comfort: 4
completeness: 5

https://github.com/skey08/scribblr
https://scribblr-blog.herokuapp.com

I feel like I learned a lot doing this homework.  I liked learning how things operate and then the "easier" way to do it.  Wish I had more time to stylize it.  I'd also like to refine what users can see if they are logged in or not.  I didn't do anything with my t.timestamps table either.

**Comment by jshawl** [comment]
:+1: Please open a pull request so I can leave code comments:
1. Fork this repository
2. copy the url of your fork
3. cd ~/path/to/your/local/scribblr
4. `git remote add origin url-of-your-fork`
5. open pull request

> Wish I had more time to stylize it.

Are you kidding? Design looks awesome!! It would be nice if posts belonged to a user rather than allowing users to type in an author.

**Comment by jshawl** [comment]
Actually, I forked your repository to leave code comments - https://github.com/skey08/scribblr/compare/master...jshawl:feedback

Let me know if you have any questions! But overall nice job on this assignment!
