### ISSUE TITLE
Rachel-scribbler

### ISSUE THREAD

**Issue by rewarren** [ga-dc/scribble#46]
https://rachel-scribbler.herokuapp.com/
https://github.com/rewarren/scribbler

comfort: 3.7
complete: 4

OK - this was tough, but i enjoyed it.  CSS was surprisingly tough too!...  my blog is mostly functioning, though it still renders an error after a blog post is submitted (though the post still saves to the db) and you can view, edit etc the post.  I had to leave it because I only realized it late. Looking forward to the project2.

**Comment by RobertAKARobin** [comment]
Ahh. Thank you for redirecting to `sign_in` after a successful `sign_up`.

Wow! Instead of using an enormous `<input>` for the post content, _please_ use `<textarea>`.

You get an error after creating a new post because of this:

```
@post = current_user.create!(post_params)
```

It means you're trying to create a user from the post params, which won't work at all! I think you meant:

```
@post = current_user.posts.create!(post_params)
```

Be careful on your indentation.

Thank you for not having `<br>` after all your `<input>`!
