### ISSUE TITLE
Melissa - Scribble Blog

### ISSUE THREAD

**Issue by msteffan** [ga-dc/scribble#7]
Comfort: 3-4/5
Completeness: 5/5

link: https://scribble-blawg.herokuapp.com/

repo: https://github.com/msteffan/scribble

**Comment by RobertAKARobin** [comment]
It looks great!

Snooty design comment: You've got 4 different fonts going on. Try to stick to 2!

Props on getting Devise working!

Instead of `redirect_to post_path(@comment.post_id)`, you can just `redirect_to post_path(@post)`.

`comments/_comment_form.html.erb` is redundant. Just `_form`.

Hm. `posts/_comment_form.html.erb` is a little confusing, too.

Great job at the hackathon!
